version: "2.2"
services:
  iris:
    image: intersystemsdc/irishealth-community:preview
    command: --check-caps false
    restart: always
    cpuset: "0-1"
    build:
      context: iris
      dockerfile: Dockerfile3
      args:
        IRIS_IMAGE: intersystemsdc/irishealth-community:preview
    ports:
      - 52773:52773
      - 1972:1972
  